/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author laboratorio
 */
public class UI_calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UI_calculadora.class.getName());
    
    double n1,n2;
    String operacao;
    List<Character> listaOperadores = new ArrayList<Character>();
    /**
     * Creates new form UI_calculadora
     */
    public UI_calculadora() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_ce = new javax.swing.JButton();
        jBtn_c = new javax.swing.JButton();
        jBtn_backSpace = new javax.swing.JButton();
        jBtn_n7 = new javax.swing.JButton();
        jBtn_n8 = new javax.swing.JButton();
        jBtn_n9 = new javax.swing.JButton();
        jBtn_op_div = new javax.swing.JButton();
        jBtn_n4 = new javax.swing.JButton();
        jBtn_n5 = new javax.swing.JButton();
        jBtn_n6 = new javax.swing.JButton();
        jBtn_op_mult = new javax.swing.JButton();
        jBtn_n1 = new javax.swing.JButton();
        jBtn_n2 = new javax.swing.JButton();
        jBtn_n3 = new javax.swing.JButton();
        jBtn_op_adic = new javax.swing.JButton();
        jBtn_n0 = new javax.swing.JButton();
        jBtn_decimal = new javax.swing.JButton();
        jBtn_op_sub = new javax.swing.JButton();
        jBtn_op_igual = new javax.swing.JButton();
        jTextF_visor = new javax.swing.JTextField();
        jLab_valor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtn_ce.setText("CE");
        jBtn_ce.setDoubleBuffered(true);
        jBtn_ce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_ce.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_ce.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_ce.setPreferredSize(new java.awt.Dimension(75, 75));

        jBtn_c.setText("C");
        jBtn_c.setDoubleBuffered(true);
        jBtn_c.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_c.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_c.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_c.setPreferredSize(new java.awt.Dimension(75, 75));

        jBtn_backSpace.setText("<-");
        jBtn_backSpace.setDoubleBuffered(true);
        jBtn_backSpace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_backSpace.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_backSpace.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_backSpace.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_backSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_backSpaceActionPerformed(evt);
            }
        });

        jBtn_n7.setText("7");
        jBtn_n7.setDoubleBuffered(true);
        jBtn_n7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n7.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n7.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n7.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n7ActionPerformed(evt);
            }
        });

        jBtn_n8.setText("8");
        jBtn_n8.setDoubleBuffered(true);
        jBtn_n8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n8.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n8.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n8.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n8ActionPerformed(evt);
            }
        });

        jBtn_n9.setText("9");
        jBtn_n9.setDoubleBuffered(true);
        jBtn_n9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n9.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n9.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n9.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n9ActionPerformed(evt);
            }
        });

        jBtn_op_div.setText("/");
        jBtn_op_div.setDoubleBuffered(true);
        jBtn_op_div.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_op_div.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_op_div.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_op_div.setPreferredSize(new java.awt.Dimension(75, 75));

        jBtn_n4.setText("4");
        jBtn_n4.setDoubleBuffered(true);
        jBtn_n4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n4.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n4.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n4.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n4ActionPerformed(evt);
            }
        });

        jBtn_n5.setText("5");
        jBtn_n5.setDoubleBuffered(true);
        jBtn_n5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n5.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n5.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n5.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n5ActionPerformed(evt);
            }
        });

        jBtn_n6.setText("6");
        jBtn_n6.setDoubleBuffered(true);
        jBtn_n6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n6.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n6.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n6.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n6ActionPerformed(evt);
            }
        });

        jBtn_op_mult.setText("*");
        jBtn_op_mult.setDoubleBuffered(true);
        jBtn_op_mult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_op_mult.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_op_mult.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_op_mult.setPreferredSize(new java.awt.Dimension(75, 75));

        jBtn_n1.setText("1");
        jBtn_n1.setDoubleBuffered(true);
        jBtn_n1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n1.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n1.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n1.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n1ActionPerformed(evt);
            }
        });

        jBtn_n2.setText("2");
        jBtn_n2.setDoubleBuffered(true);
        jBtn_n2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n2.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n2.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n2.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n2ActionPerformed(evt);
            }
        });

        jBtn_n3.setText("3");
        jBtn_n3.setDoubleBuffered(true);
        jBtn_n3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n3.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n3.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n3.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n3ActionPerformed(evt);
            }
        });

        jBtn_op_adic.setText("+");
        jBtn_op_adic.setDoubleBuffered(true);
        jBtn_op_adic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_op_adic.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_op_adic.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_op_adic.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_op_adic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_op_adicActionPerformed(evt);
            }
        });

        jBtn_n0.setText("0");
        jBtn_n0.setDoubleBuffered(true);
        jBtn_n0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_n0.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_n0.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_n0.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_n0ActionPerformed(evt);
            }
        });

        jBtn_decimal.setText(".");
        jBtn_decimal.setDoubleBuffered(true);
        jBtn_decimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_decimal.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_decimal.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_decimal.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_decimalActionPerformed(evt);
            }
        });

        jBtn_op_sub.setText("-");
        jBtn_op_sub.setDoubleBuffered(true);
        jBtn_op_sub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_op_sub.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_op_sub.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_op_sub.setPreferredSize(new java.awt.Dimension(75, 75));

        jBtn_op_igual.setText("=");
        jBtn_op_igual.setDoubleBuffered(true);
        jBtn_op_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_op_igual.setMaximumSize(new java.awt.Dimension(60, 45));
        jBtn_op_igual.setMinimumSize(new java.awt.Dimension(60, 45));
        jBtn_op_igual.setPreferredSize(new java.awt.Dimension(75, 75));
        jBtn_op_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_op_igualActionPerformed(evt);
            }
        });

        jTextF_visor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jBtn_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_op_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextF_visor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn_backSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn_op_div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn_op_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn_op_adic, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn_op_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLab_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLab_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextF_visor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_backSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_op_div, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_op_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_op_adic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_op_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_n0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_op_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n1ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"1");
    }//GEN-LAST:event_jBtn_n1ActionPerformed

    private void jBtn_n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n2ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"2");
    }//GEN-LAST:event_jBtn_n2ActionPerformed

    private void jBtn_n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n3ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"3");
    }//GEN-LAST:event_jBtn_n3ActionPerformed

    private void jBtn_n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n4ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"4");
    }//GEN-LAST:event_jBtn_n4ActionPerformed

    private void jBtn_n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n5ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"5");
    }//GEN-LAST:event_jBtn_n5ActionPerformed

    private void jBtn_n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n6ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"6");
    }//GEN-LAST:event_jBtn_n6ActionPerformed

    private void jBtn_n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n7ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"7");
    }//GEN-LAST:event_jBtn_n7ActionPerformed

    private void jBtn_n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n8ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"8");
    }//GEN-LAST:event_jBtn_n8ActionPerformed

    private void jBtn_n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n9ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"9");
    }//GEN-LAST:event_jBtn_n9ActionPerformed

    private void jBtn_n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_n0ActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+"0");
    }//GEN-LAST:event_jBtn_n0ActionPerformed

    private void jBtn_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_decimalActionPerformed
        jTextF_visor.setText(jTextF_visor.getText()+".");
    }//GEN-LAST:event_jBtn_decimalActionPerformed

    private void jBtn_backSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_backSpaceActionPerformed
        jTextF_visor.setText(jTextF_visor.getText().substring(0,jTextF_visor.getText().length()-1));
    }//GEN-LAST:event_jBtn_backSpaceActionPerformed

    private void jBtn_op_adicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_op_adicActionPerformed
        jLab_valor.setText(jTextF_visor.getText()+"+");
        n1 = Double.parseDouble(jTextF_visor.getText());
        operacao = "soma";
        jTextF_visor.setText("");
    }//GEN-LAST:event_jBtn_op_adicActionPerformed

    private void jBtn_op_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_op_igualActionPerformed
        double resultado;
        n2 = Double.parseDouble(jTextF_visor.getText());
        if(operacao == "soma"){
            resultado = n1 + n2;
            jLab_valor.setText(n1+"+"+n2+"=");
            jTextF_visor.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_jBtn_op_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UI_calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_backSpace;
    private javax.swing.JButton jBtn_c;
    private javax.swing.JButton jBtn_ce;
    private javax.swing.JButton jBtn_decimal;
    private javax.swing.JButton jBtn_n0;
    private javax.swing.JButton jBtn_n1;
    private javax.swing.JButton jBtn_n2;
    private javax.swing.JButton jBtn_n3;
    private javax.swing.JButton jBtn_n4;
    private javax.swing.JButton jBtn_n5;
    private javax.swing.JButton jBtn_n6;
    private javax.swing.JButton jBtn_n7;
    private javax.swing.JButton jBtn_n8;
    private javax.swing.JButton jBtn_n9;
    private javax.swing.JButton jBtn_op_adic;
    private javax.swing.JButton jBtn_op_div;
    private javax.swing.JButton jBtn_op_igual;
    private javax.swing.JButton jBtn_op_mult;
    private javax.swing.JButton jBtn_op_sub;
    private javax.swing.JLabel jLab_valor;
    private javax.swing.JTextField jTextF_visor;
    // End of variables declaration//GEN-END:variables
}
