/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg;

import java.awt.Event;

/**
 *
 * @author laboratorio
 */
public class formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formulario.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lab_txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_texto = new javax.swing.JTextArea();
        jBtn_mostrarTxt = new javax.swing.JButton();
        txtF_mensagem = new javax.swing.JTextField();
        btn_addMsg = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lab_txt.setText("Texto:");

        txtA_texto.setColumns(20);
        txtA_texto.setRows(5);
        jScrollPane1.setViewportView(txtA_texto);

        jBtn_mostrarTxt.setText("Mostrar Texto");
        jBtn_mostrarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_mostrarTxtActionPerformed(evt);
            }
        });

        txtF_mensagem.setText("Aqui vai a mensagem");
        txtF_mensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF_mensagemActionPerformed(evt);
            }
        });

        btn_addMsg.setText("Add Msg");
        btn_addMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtn_mostrarTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab_txt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtF_mensagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_addMsg))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF_mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addMsg))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_mostrarTxt)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_mostrarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_mostrarTxtActionPerformed
        txtA_texto.setText("Cliquei no botão e estou enviando aqui no txaTexto");

        
    }//GEN-LAST:event_jBtn_mostrarTxtActionPerformed

    private void btn_addMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addMsgActionPerformed
        //txtA_texto.setText(txtF_mensagem.getText());
        if(!txtA_texto.getText().isBlank()){
            txtA_texto.append("\n"+txtF_mensagem.getText());
        } else { 
            txtA_texto.append(txtF_mensagem.getText() + "\n");
        }
        txtF_mensagem.setText("");
    }//GEN-LAST:event_btn_addMsgActionPerformed

    private void txtF_mensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF_mensagemActionPerformed
        if(!txtA_texto.getText().isBlank()){
            txtA_texto.append("\n"+txtF_mensagem.getText());
        } else { 
            txtA_texto.append(txtF_mensagem.getText() + "\n");
        }
        txtF_mensagem.setText("");
    }//GEN-LAST:event_txtF_mensagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addMsg;
    private javax.swing.JButton jBtn_mostrarTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lab_txt;
    private javax.swing.JTextArea txtA_texto;
    private javax.swing.JTextField txtF_mensagem;
    // End of variables declaration//GEN-END:variables
}
